### PR TITLE
I113 highermoments

### PR DESCRIPTION
**Pull request by benthestatistician**
I've added an "`inferentials.calculator`" argument to `balanceTest()` in order to enable to the function to support new test statistics alongside of the old.  It's well for other collaborators to review and perhaps comment on this concept even as Mark and I continue working on setting up the first of these newer test statistics; thus this merge request. 

Secondarily I'd also have you take a look at 698ee93, which would introduce yet another argument, one that I foresee a role for in some of these newer statistics.  (It's reverted in 031bb75, as there's no role for it presently or in the new version we're currently working on.) Perhaps some of the arguments can be collected into an "`options`" or "`control`" argument, expecting a list.

### CODE REVIEW

**Comment by benthestatistician** [comment]
(This is mostly directed to @jwbowers , but @josherrickson your comments would be welcome also.  If you can't get to it immediately you won't hold us up as we'll just keep working on the branch.)

**Comment by josherrickson** [comment]
No real comments on substance; but documentation for `inferentials.calculator` is sparse.

**Comment by jwbowers** [comment]
This looks good to me. Nice tests. I'm glad to see this flexibility.

**Comment by jwbowers** [comment]
I'm merging this in.

**Comment by benthestatistician** [comment]
Thanks, Jake and Josh. (Josh, I addressed spareseness of
`inferentials.calculator` documentation not by filling it out but by
adding a disclaimer; see 5f60bfe / 5543f9e.)

**Pull request merged**
